### ISSUE TITLE
Valores por defecto

### ISSUE THREAD

**Issue by juanda99** [catedu/moodle-docker-deploy#1]
Aparecían en el script:

```
MOODLE_ADMIN_USER="adminuser"
MOODLE_ADMIN_PASSWORD="camb1ameperoYA"
MOODLE_ADMIN_EMAIL="admin@centro.com"
MOODLE_LANG="es"
MOODLE_SITE_NAME="AEduca"
MOODLE_SITE_FULLNAME="AEduca del CPI/IES Mi Centro"
```

Los he movido a env-sample que se carga antes de empezar el script (donde está también los datos de conexión root). Pero.... no estaría mejor meterlos ya simplemente en el template?

Si vienen como parámetros se podrían cambiar mediante un sed  [@fácilmente.](url)

**Comment by sannacho** [comment]
Creo que queda "mejor" como lo has dejado. En .env a nivel del script de creación de moodle, donde se define el patrón base junto a los datos de conexión necesarios para la BD, y así queda el template más limpio y como información "inalterable".
Cierro incidencia
