### ISSUE TITLE
opción EXTERNAL_DB 

### ISSUE THREAD

**Issue by juanda99** [catedu/moodle-docker-deploy#2]
Siempre va a ser externa, la IP debería ir en el .env. Quitamos lo que sobra?

**Comment by sannacho** [comment]
Yo la opción de externa creo que se podría dejar...por si en alguna otra infraestructura se va a usar interna (nuestra o de alguien que haga uso del código). 
Dejar la funcionalidad no cuesta nada, ya que por defecto lo dejamos a externa, y lo hacemos más versátil

**Comment by juanda99** [comment]
A tu gusto. En el momento que se haga un deploy de varios moodle entiendo que lo primero que se hace es separar bbdd de frontend, así que en principio no veo un uso claro. Para pruebas ya está el repo de [moodle-docker-production](https://github.com/catedu/moodle-docker-production)

**Comment by sannacho** [comment]
Observo que ya está quitado, así que habría que volver a ponerlo...por tanto, lo dejamos como está (sin la opción)
