### ISSUE TITLE
Simplicar user y db_name

### ISSUE THREAD

**Issue by juanda99** [catedu/moodle-docker-deploy#3]
usage: createMoodle.sh [-e mail_admin] [-l es|fr|..] [-n "full_name"] -u "url" [-i] shortname

Yo haría cómo único parámetro "obligatorio" la url.
El shortname puede venir de centro1.catedu.es -> centro1
El nombre de la bbdd y del usuario también podrían ser ese centro1:

```

MOODLE_DB_NAME="$(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)"
MOODLE_MYSQL_USER=$(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

```

Y el directorio donde se instala también. Ganamos simplicidad.

**Comment by sannacho** [comment]
Solucionado ya
