### ISSUE TITLE
Instalar plugins sin referencia a la versión

### ISSUE THREAD

**Issue by deleyva** [catedu/moodle-docker-deploy#4]
¿No sería mejor no indicar la versión en [plugins-sample.sh](https://github.com/deleyva/moodle-docker-deploy/blob/master/template/init-scripts/plugins-sample.sh)?

En la [documentación](https://moosh-online.com/commands/#plugin-install) dice que si no se indica la versión instala la última versión disponible para la versión de moodle en la que se ejecute el comando.

Example 1: install a specific version
```
moosh plugin-install --release 20160101 mod_quickmail
```

Example 2: install the latest release supported by current moodle version
```
moosh plugin-install block_checklist
```

**Comment by juanda99** [comment]
Hecho en el ejemplo
