### ISSUE TITLE
Incluir importación del tema con imágenes y ajustes

### ISSUE THREAD

**Issue by deleyva** [catedu/moodle-docker-deploy#5]
Creo que la forma más limpia de añadir los ajustes del tema es exportar la configuración, una vez la tengamos clara:
```
moosh -n theme-settings-export --themename snap
```
... y luego importarla importarla en cada instancia nueva:
```
moosh -n theme-settings-import snap_settings_1558197087.tar.gz
```

**Comment by juanda99** [comment]
Tenemos un problema, moosh no funciona bien tmuras/moosh#312
Me veo debugeando php y haciendo PR :-(

**Comment by deleyva** [comment]
Veo que al final lo has conseguido ¿no?

**Comment by juanda99** [comment]
Hay otro error, luego a ver si lo miro y cierro issue.

**Comment by deleyva** [comment]
A mí me sale 
```
moodle        | /init-scripts/snap_settings_1589792845.tar.gz ignored, wrong extension
```

De todas formas, esto luego podemos configurarlo usando `moosh config-set`, así que si no se puede así, lo hacemos de la otra manera.

**Comment by juanda99** [comment]
Cambiada estructura en moodle-docker-production, en cuanto esté testeada la ponemos aquí.
Hacer un tar.gz en linux es complicado para compatibilizar con plugin, ver tmuras/moosh#316
En el /init-scripts hay un directorio snap-settings donde podemos tocar "a pelo" el xml.

**Comment by juanda99** [comment]
Básicamente eso dice que no va a ejecutar ese fichero, pero quitaré el
mensaje, no aporta, solo despista.
